### ISSUE TITLE
Missing Go source files

### ISSUE THREAD

**Issue by andrewrgoss** [jeffizhungry/logrus#1]
When trying to get your modified Logrus package:

    $ go get github.com/jeffizhungry/logrus
    go build github.com/Sirupsen/logrus/hooks/syslog: no buildable Go source files in C:\Users\andgoss\GoLangCode\src\github.com\Sirupsen\logrus\hooks\syslog

**Comment by jeffizhungry** [comment]
The only way I was able to reproduce your issue was if you did the following:
```
go get github.com/Sirupsen/logrus
rm $GOPATH/src/github.com/Sirupsen/logrus/hooks/syslog/*
go get github.com/jeffizhungry/logrus
```

Easy solution, just do this:
```
rm -rf $GOPATH/src/github.com/Sirupsen
go get github.com/jeffizhungry/logrus
```

**Comment by andrewrgoss** [comment]
Still getting the same issue, even when running the solution commands you provided to remove the original Sirupsen src package. Any other ideas? Hoping to use your logging interface, I think it is exactly what I have been looking for.

**Comment by jeffizhungry** [comment]
I'll try to help out as much as I can! Usually the error messages the go toolchain shows are pretty descriptive. Can you verify that there are **.go** files in your directory:

`C:\Users\andgoss\GoLangCode\src\github.com\Sirupsen\logrus\hooks\syslog`

Also this is maybe more of stretch, but do you have multiple GOPATH set? Because that can cause some issues.

**Comment by jeffizhungry** [comment]
Or if `go get github.com/jeffizhungry/logrus` really doesn't work, then you can do a manual install too:
```
cd $GOPATH/src/github.com/jeffizhungry
git clone https://github.com/jeffizhungry/logrus
cd $GOPATH/src/github.com/jeffizhungry/logrus/
go get ./...
```
The last line just fetches all the dependencies needed to build my package.

**Comment by andrewrgoss** [comment]
Really appreciate your help with this Jeff. I can confirm there are .go files in this directory: C:\Users\andgoss\GoLangCode\src\github.com\Sirupsen\logrus\hooks\syslog
The files are syslog.go and syslog_test.go

I verified that I only have one GOPATH set. I'm using a Windows OS and checked the environment variables to confirm.

For the manual install approach, I was able to git clone your package without any issues. However, when fetching the dependencies...

    $ go get ./...
    go build github.com/Sirupsen/logrus/hooks/syslog: no buildable Go source files in C:\Users\andgoss\GoLangCode\src\github.com\Sirupsen\logrus\hooks\syslog

Same message once again. I don't get what is going on here, the Go files are clearly in the correct directory. I'm not clear on why they can't be referenced when trying to import your package.

<img width="394" alt="capture" src="https://cloud.githubusercontent.com/assets/1461386/12333345/abebfeec-bac1-11e5-8781-bc9fd4d1c33f.PNG">

**Comment by jeffizhungry** [comment]
Ahh, I know what you're problem is. It is because the syslog hook is linux specific, so Sirupsen put build tags:

`// +build !windows,!nacl,!plan9`

in his **syslog.go** to prevent people from mistakenly compiling it on Windows.

I don't intend to make my repo support Windows or add custom hooks anytime soon.
Feel free to fork this and add whatever other Windows hooks you might use.

**Comment by andrewrgoss** [comment]
Ah I missed that, makes sense now. We use a Linux environment - I was just testing on my local machine with Cygwin. Thanks again for your assistance!
